databases:
  - name: vinylswapp
    databaseName: vinylswapp
    user: vinylswapp_user

services:
  - type: web
    name: vinylswapp
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: vinylswapp
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false